### PR TITLE
adding ChannelMath

### PR DESCRIPTION
**Pull request by nicholascarroll**
Hi Francois here is a channel math expression node that you might like to add to your collection. It is easy for artists.

### CODE REVIEW

**Comment by devernay** [comment]
Hi Nicholas,
We already have two expression nodes (SeExpr and CImgExpr), is there anything more in this one that justifies including it in the main dstribution?
Fred

**Comment by nicholascarroll** [comment]
Yes, it is for a different purpose. ChannelMath like a shuffle that can do math. This is for simple expressions and is easy to learn and quick to work with. For larger expressions or more sophisticated functions, use SeExpr. I made the syntax compatible with SeExpr for that reason.

I had a look at ClmgExpr but it's just one small field. Am I missing something?

**Comment by devernay** [comment]
The thing is that SeExpr is already very simple, already a de facto standard for artists, and already optimized. Everything that can be done with ChannelMath is doable with SeExpr, so maybe it's just a matter of writing a better documentation for SeExpr? What do you think is missing in SeExpr from your point of view?

CImgExpr could be extended with the same set of parameters as SeExpr if needed. The main advantage over SeExpr is that it accepts loops (it's not just an expression language).

**Comment by nicholascarroll** [comment]
Fair enough, well thanks for considering it. The advantage of ChannelMath is that it has a separate field for each channel. I think the current version of SeExpr is pretty good.

**Comment by devernay** [comment]
One can use different expressions for each channel in SeExpr, and rembine them in a vector, as in:
[Cs[0]*x1,Cs[1]*x2,Cs[2]*x3]

**Comment by devernay** [comment]
btw @nicholascarroll if you feel like contributing there is a [todo list](https://github.com/MrKepzie/Natron/wiki/Google-Summer-of-Code-GSoC-ideas#openfx-plugins)
we may ask you to sign a [CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement) for inclusion in the official distribution

**Comment by nicholascarroll** [comment]
Thanks. My C++ is very rudimentary and am not interested in improving it, but this year I will publish a download web page for ChannelMath and a keyer plugin I am working on. These will come with a technical support agreement, user guide and training video. If that goes well I will probably be able to offer contributions to those aspects of the Natron project.

**Comment by devernay** [comment]
this is great news! Natron is also here so that others can easily make new plugins. Please keep us informed.

**Comment by nicholascarroll** [comment]
FYI have cancelled plan to offer tech support on those two plugins. For just a plugin its not needed.

**Pull request closed without merging**
